name: factoscope
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Packages n√©cessaires
  provider: ^6.0.5
  sqflite: ^2.0.0+4
  path: ^1.8.0
  get_it: ^7.6.0
  flutter_svg: ^2.0.7
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  video_player: ^2.9.2
  audioplayers: ^6.2.0
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_android.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/data/AppData/
    - lib/data/AppData/Module1/
    - lib/data/AppData/Module1/Cours1/
    - lib/data/AppData/Module1/Cours2/
