name: seriouse_game
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Base de données
  sqflite: ^2.0.0+4
  path: ^1.8.0

  # Architecture & injection
  get_it: ^7.6.0
  provider: ^6.1.2   # ← AJOUT ESSENTIEL POUR TON MVVM

  # UI & assets
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.8

  # Media
  video_player: ^2.9.2
  audioplayers: ^6.2.0

  # Navigation
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/data/AppData/
    - lib/data/AppData/CharteFactoscope/
    - lib/data/AppData/Module1/Cours1/
    - lib/data/AppData/Module1/Cours2/
    - lib/data/ArchiveBestPattern2QCM/
